version: "3.7"

services:
  db:
    image: postgres:16.2
    hostname: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/script.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'

  pgadmin:
    image: dpage/pgadmin4:8.3
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres:


networks:
  default:
    driver: bridge
